# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.5.1+26.2
maven_group=de.dafuqs
archives_base_name = revelationary

# https://fabricmc.net/develop/
fabric_api_version=0.153.0+26.2
jade_version=26.2.5+fabric
wthit_version=19.0.1
#rei_version=20.0.811
jei_version=30.2.0.15
