# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.5.1+26.1
maven_group=de.dafuqs
archives_base_name = revelationary

# https://fabricmc.net/develop/
fabric_api_version=0.145.1+26.1

jade_version=26.0.4+fabric
wthit_version=19.0.0
#rei_version=20.0.811
jei_version=29.2.0.20
